--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ani/Pictures/wallpapers/wallpaper.png"

-- Special
background="#0d1420"
foreground="#c2c4c7"
cursor="#c2c4c7"

-- Colors
color0="#0d1420"
color1="#502A49"
color2="#6C2C52"
color3="#5D4359"
color4="#9B1B5B"
color5="#B54C6D"
color6="#D19476"
color7="#c2c4c7"
color8="#5d6571"
color9="#502A49"
color10="#6C2C52"
color11="#5D4359"
color12="#9B1B5B"
color13="#B54C6D"
color14="#D19476"
color15="#c2c4c7"
