--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ani/Pictures/Wallpapers/wallpaper.png"

-- Special
background="#130908"
foreground="#c4c1c1"
cursor="#c4c1c1"

-- Colors
color0="#130908"
color1="#891F14"
color2="#892D1A"
color3="#8F082D"
color4="#AA083A"
color5="#903923"
color6="#9A452D"
color7="#c4c1c1"
color8="#6b5a57"
color9="#891F14"
color10="#892D1A"
color11="#8F082D"
color12="#AA083A"
color13="#903923"
color14="#9A452D"
color15="#c4c1c1"
