set background=dark
if exists('g:colors_name')
hi clear
if exists('syntax_on')
syntax reset
endif
endif
let g:colors_name = 'lushwal'
highlight Normal guifg=#C3C1C1 guibg=#120808 guisp=NONE blend=NONE gui=NONE
highlight! link User Normal
highlight Bold guifg=#C3C1C1 guibg=#120808 guisp=NONE blend=NONE gui=bold
highlight Boolean guifg=#8F0F1C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Character guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight ColorColumn guifg=#877673 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Comment guifg=#C3C1C1 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight Conceal guifg=#6B5A57 guibg=#120808 guisp=NONE blend=NONE gui=NONE
highlight! link Whitespace Conceal
highlight Conditional guifg=#F7D050 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Constant guifg=#8F0F1C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Cursor guifg=#120808 guibg=#C3C1C1 guisp=NONE blend=NONE gui=NONE
highlight CursorColumn guifg=#877673 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight CursorLine guifg=NONE guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight CursorLineNr guifg=#C3C1C1 guibg=#120808 guisp=NONE blend=NONE gui=NONE
highlight Debug guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Define guifg=#F7D050 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Delimiter guifg=#8D2416 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticError guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticHint guifg=#9A442D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticInfo guifg=#AA083B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticUnderlineError guifg=#8A2014 guibg=NONE guisp=#8A2014 blend=NONE gui=underline
highlight DiagnosticUnderlineHint guifg=#9A442D guibg=NONE guisp=#9A442D blend=NONE gui=underline
highlight DiagnosticUnderlineInfo guifg=#AA083B guibg=NONE guisp=#AA083B blend=NONE gui=underline
highlight DiagnosticUnderlineWarn guifg=#91082D guibg=NONE guisp=#91082D blend=NONE gui=underline
highlight DiagnosticWarn guifg=#91082D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiffAdd guifg=#892D1A guibg=#6B5A57 guisp=NONE blend=NONE gui=bold
highlight! link DiffAdded DiffAdd
highlight DiffChange guifg=#A59D9C guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight DiffDelete guifg=#8A2014 guibg=#6B5A57 guisp=NONE blend=NONE gui=bold
highlight! link DiffRemoved DiffDelete
highlight! link diffRemoved DiffDelete
highlight DiffFile guifg=#8A2014 guibg=#120808 guisp=NONE blend=NONE gui=NONE
highlight DiffLine guifg=#AA083B guibg=#120808 guisp=NONE blend=NONE gui=NONE
highlight DiffNewFile guifg=#892D1A guibg=#120808 guisp=NONE blend=NONE gui=NONE
highlight DiffText guifg=#AA083B guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight Directory guifg=#AA083B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight EndOfBuffer guifg=#C3C1C1 guibg=#120808 guisp=NONE blend=NONE gui=NONE
highlight Error guifg=#8A2014 guibg=#C3C1C1 guisp=NONE blend=NONE gui=NONE
highlight ErrorMsg guifg=#8A2014 guibg=#120808 guisp=NONE blend=NONE gui=NONE
highlight Exception guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Float guifg=#8F0F1C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight FoldColumn guifg=#AA083B guibg=#120808 guisp=NONE blend=NONE gui=NONE
highlight Folded guifg=#C3C1C1 guibg=#6B5A57 guisp=NONE blend=NONE gui=italic
highlight Function guifg=#AA083B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Identifier guifg=#9A442D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight IncSearch guifg=#6B5A57 guibg=#8F0F1C guisp=NONE blend=NONE gui=NONE
highlight Include guifg=#AA083B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Italic guifg=#C3C1C1 guibg=#120808 guisp=NONE blend=NONE gui=italic
highlight Keyword guifg=#F7D050 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Label guifg=#91082D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight LineNr guifg=#A59D9C guibg=#120808 guisp=NONE blend=NONE gui=NONE
highlight Macro guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MatchParen guifg=#C3C1C1 guibg=#A59D9C guisp=NONE blend=NONE gui=NONE
highlight MiniCompletionActiveParameter guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniCursorword guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight! link MiniCursorwordCurrent MiniCursorword
highlight MiniIndentscopePrefix guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=nocombine
highlight MiniIndentscopeSymbol guifg=#6B5A57 guibg=#120808 guisp=NONE blend=NONE gui=NONE
highlight MiniJump guifg=#AA083B guibg=NONE guisp=#A59D9C blend=NONE gui=underline
highlight MiniJump2dSpot guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=undercurl
highlight MiniStarterCurrent guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterFooter guifg=#AA083B guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterHeader guifg=#AA083B guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterInactive guifg=#C3C1C1 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight MiniStarterItem guifg=#C3C1C1 guibg=#120808 guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemBullet guifg=#8D2416 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemPrefix guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterQuery guifg=#892D1A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterSection guifg=#8D2416 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineDevinfo guifg=#C3C1C1 guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFileinfo guifg=#C3C1C1 guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFilename guifg=#91082D guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineInactive guifg=#877673 guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeCommand guifg=#120808 guibg=#9A442D guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeInsert guifg=#120808 guibg=#AA083B guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeNormal guifg=#120808 guibg=#892D1A guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeOther guifg=#120808 guibg=#F7D050 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeReplace guifg=#120808 guibg=#8A2014 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeVisual guifg=#120808 guibg=#8F0F1C guisp=NONE blend=NONE gui=NONE
highlight MiniSurround guifg=#6B5A57 guibg=#8F0F1C guisp=NONE blend=NONE gui=NONE
highlight MiniTablineCurrent guifg=#A59D9C guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineFill guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniTablineHidden guifg=#892D1A guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedCurrent guifg=#C3C1C1 guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedHidden guifg=#877673 guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedVisible guifg=#C3C1C1 guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineVisible guifg=#A59D9C guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight MiniTestEmphasis guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestFail guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestPass guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTrailspace guifg=#8A2014 guibg=#C3C1C1 guisp=NONE blend=NONE gui=NONE
highlight ModeMsg guifg=#892D1A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MoreMsg guifg=#892D1A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight NonText guifg=#A59D9C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Number guifg=#8F0F1C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Operator guifg=#C3C1C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PMenu guifg=#C3C1C1 guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight PMenuSel guifg=#C3C1C1 guibg=#AA083B guisp=NONE blend=NONE gui=NONE
highlight PmenuSbar guifg=#877673 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PmenuThumb guifg=#C3C1C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PreProc guifg=#91082D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Question guifg=#AA083B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Repeat guifg=#91082D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Search guifg=#A59D9C guibg=#91082D guisp=NONE blend=NONE gui=NONE
highlight! link MiniTablineTabpagesection Search
highlight SignColumn guifg=#877673 guibg=#120808 guisp=NONE blend=NONE gui=NONE
highlight Special guifg=#9A442D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialChar guifg=#8D2416 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialKey guifg=#A59D9C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpellBad guifg=#8A2014 guibg=NONE guisp=#8A2014 blend=NONE gui=underline
highlight SpellCap guifg=#91082D guibg=NONE guisp=#91082D blend=NONE gui=underline
highlight SpellLocal guifg=#9A442D guibg=NONE guisp=#9A442D blend=NONE gui=underline
highlight SpellRare guifg=#F7D050 guibg=NONE guisp=#F7D050 blend=NONE gui=underline
highlight Statement guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight StatusLine guifg=#C3C1C1 guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight StatusLineNC guifg=#877673 guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight StatusLineTerm guifg=#892D1A guibg=#892D1A guisp=NONE blend=NONE gui=NONE
highlight StatusLineTermNC guifg=#91082D guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight StorageClass guifg=#91082D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight String guifg=#892D1A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Structure guifg=#F7D050 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight TabLine guifg=#A59D9C guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight TabLineFill guifg=#A59D9C guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight TabLineSel guifg=#892D1A guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight Tag guifg=#91082D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Title guifg=#AA083B guibg=NONE guisp=NONE blend=NONE gui=bold
highlight Todo guifg=#91082D guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight TooLong guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Type guifg=#91082D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Typedef guifg=#91082D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Underlined guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight VertSplit guifg=#C3C1C1 guibg=#120808 guisp=NONE blend=NONE gui=NONE
highlight! link WinSeparator VertSplit
highlight Visual guifg=#120808 guibg=#877673 guisp=NONE blend=NONE gui=NONE
highlight VisualNOS guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WarningMsg guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WildMenu guifg=#C3C1C1 guibg=#AA083B guisp=NONE blend=NONE gui=NONE
highlight WinBar guifg=#C3C1C1 guibg=#120808 guisp=NONE blend=NONE gui=NONE
highlight WinBarNC guifg=#877673 guibg=#120808 guisp=NONE blend=NONE gui=NONE
highlight gitCommitOverflow guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight gitCommitSummary guifg=#892D1A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpCommand guifg=#91082D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpExample guifg=#91082D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @attribute guifg=#AA083B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @boolean guifg=#AA083B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character guifg=#91082D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character.special guifg=#8D2416 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @comment guifg=#C3C1C1 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @conditional guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.builtin guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.macro guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constructor guifg=#C3C1C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @debug guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @define guifg=#F7D050 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @exception guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @field guifg=#892D1A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @float guifg=#AA083B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function guifg=#AA083B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.builtin guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.macro guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @include guifg=#9A442D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword guifg=#F7D050 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.function guifg=#9A442D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.operator guifg=#F7D050 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @label guifg=#9A442D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @method guifg=#AA083B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @namespace guifg=#AA083B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @none guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @number guifg=#AA083B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @operator guifg=#C3C1C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @parameter guifg=#91082D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @preproc guifg=#91082D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @property guifg=#91082D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.bracket guifg=#C3C1C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.delimiter guifg=#C3C1C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.special guifg=#9A442D guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @repeat guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @storageclass guifg=#91082D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string guifg=#AA083B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.escape guifg=#892D1A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.regex guifg=#892D1A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.special guifg=#8D2416 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @symbol guifg=#9A442D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag guifg=#91082D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.attribute guifg=#9A442D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.delimiter guifg=#9A442D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text guifg=#892D1A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.bold guifg=#91082D guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.danger guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.diff.add guifg=#892D1A guibg=#6B5A57 guisp=NONE blend=NONE gui=bold
highlight @text.diff.delete guifg=#8A2014 guibg=#6B5A57 guisp=NONE blend=NONE gui=bold
highlight @text.emphasis guifg=#F7D050 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @text.environment guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.environment.name guifg=#91082D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.literal guifg=#892D1A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.math guifg=#9A442D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.note guifg=#9A442D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.reference guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.strike guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=strikethrough
highlight @text.title guifg=#AA083B guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.todo guifg=#91082D guibg=#6B5A57 guisp=NONE blend=NONE gui=NONE
highlight @text.underline guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight @text.uri guifg=NONE guibg=#6B5A57 guisp=NONE blend=NONE gui=underline
highlight @type guifg=#AA083B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.builtin guifg=#AA083B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.definition guifg=#91082D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable guifg=#91082D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable.builtin guifg=#8A2014 guibg=NONE guisp=NONE blend=NONE gui=NONE
